name: flutter_experiments
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animate_do: ^1.7.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  lipsum: ^1.0.1
  time:
  flutter_hooks:
  flutter_portal: ^0.3.0
  get_it_mixin:
  provider:
  tuple:
  url_launcher: ^5.7.10
  random_color:
  scrollable_positioned_list: ^0.1.8
  statsfl:
  syncfusion_flutter_sliders: ^18.3.53-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  peanut: ^3.5.1
  build_runner:
  build_web_compilers:
flutter:
  uses-material-design: true
# flutter pub global run peanut:peanut
# flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true